### PR TITLE
US63977 Change temp LOs from relying on custom id and instead on object property

### PR DESCRIPTION
**Pull request by mdedys**
- Changed check for object property
- Updated tests

### CODE REVIEW

**Comment by mdedys** [comment]
Authoring and PLO Management PRs will be created once this is published

**Comment by LavaFields** [comment]
It might be worth adding some README.md documentation about the new isTempOutcome property.

**Comment by LavaFields** [comment]
:+1:

**Comment by mdedys** [comment]
Good idea. Will add documentation

**Pull request merged**
