### PR TITLE
Root temp LO being added to registry payload

### PR DESCRIPTION
**Pull request by mdedys**
- added check to see if new root exists

### CODE REVIEW

**Comment by LavaFields** [comment]
Is this to deal with a bug in an FRA?

This behaviour appears to specific to how some of our FRAs deal with unsaved outcomes. We may switch to outcomes that are uri based in the future, which wouldn't be compatible with this change.

**Comment by mdedys** [comment]
Yes this deals with a bug i found with the plo management app. A temp node was being put into payload into the service which caused the put call to fail. If we switch to uri based then this would have to change. The plo-management and authoring app use this function.

**Comment by LavaFields** [comment]
How hard would it be to avoid saving temp nodes in the plo management app instead?

**Comment by mdedys** [comment]
The problem is that "temp" nodes are added to registry objectives list in order to display in the list when rendering. The current approach was to run through this function prior to calling the PUT for lores. This problem generally arises when the connection is slightly slower. 

This problem can be caused by creating a LO and then preform a put action immediately after before it completes.

Ex.  Create outcome -> POST Authored Call Fires 
       Delete Outcome -> PUT Registry Call Fires ( There is a temp node in the registry list )
       Bulk Create Outcome  Fires
       PUT Registry Fires

Queuing library will queue the requests but if the POST Authored request is a bit slower you can trigger an action before Bulk Create gets called in the FRA and queued

In order to prevent "temp" nodes in the request we would have to lock the UI when a outcome is saving. ( until the bulk create call returns ). I don't see another way of rendering temp outcomes. Or put a wrapper over the queueing library to enforce  POST Authored ->BulkCreate always happen as a sequence and no other request can be fired before that is complete.

**Comment by mdedys** [comment]
Actually instead of relying on the id I will add a field of temp: true. I will still leave this function but just change the check to check for this field. I will make a User story for this to cover this for authoring FRA and PLO FRA

**Comment by LavaFields** [comment]
I like your temp property idea. Relying on not being able to convert the id to a hides what's actually going on and doesn't support the possibility of objective URIs.

**Comment by mdedys** [comment]
I am going to close this pull request and open it under a new branch for the story I am going to create. It will cover modifying this library to support the temp property on the object and updating the FRAs that use temp outcomes.

**Comment by mdedys** [comment]
#4

**Comment by mdedys** [comment]
This issue has been resolved in #5

**Pull request closed without merging**
